
ALTER TABLE orders ADD COLUMN payment_method VARCHAR(16) NOT NULL DEFAULT 'arrears';
ALTER TABLE orders ADD COLUMN paid TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN arrears_unit_id INTEGER NULL;
ALTER TABLE orders ADD COLUMN arrears_unit_name VARCHAR(128) NOT NULL DEFAULT '';
ALTER TABLE products ADD COLUMN cost_price NUMERIC(14,4) NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN stock INTEGER NOT NULL DEFAULT 0;
ALTER TABLE shipper_addresses ADD COLUMN origin_address VARCHAR(512) NULL;
ALTER TABLE shipper_addresses ADD COLUMN origin_lat NUMERIC(10,7) NULL;
ALTER TABLE shipper_addresses ADD COLUMN origin_lng NUMERIC(10,7) NULL;
